### ISSUE TITLE
Forkでやるか、Branchでやるか。

### ISSUE THREAD

**Issue by Kenyat1989** [yokome-yokone/frontend_mainpage_v2#2]
Forkで作業を進めると、プルリクが送られないと他のメンバーの作業進捗が見えないかなと。それならBranchつくってPushしていって、他のメンバーの作業状況が見えるほうがいいなって思った。

**Comment by Kenyat1989** [comment]
Forkの場合でも各メンバーのリポジトリを見に行けばいいのか。

**Comment by rot1024** [comment]
確かに一理あります。ただ、プルリクはコードレビューができるという利点があります。どちらでもいいと思いますが、まだ他の人にブランチについてレクチャーしてなかったような。

**Comment by Kenyat1989** [comment]
ブランチからプルリクを送る方法ってないのかな？
ここはダイレクトにマージになる？

**Comment by kurohune538** [comment]
ブランチからマージの際にプルリク送る方法もありますよ！

**Comment by Kenyat1989** [comment]
ということはコードレビューも可能＼(^o^)／
